# Generated by Django 4.1.7 on 2023-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quidditch", "0003_players"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="division",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teams",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
