# Generated by Django 4.1.7 on 2023-03-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quidditch", "0004_alter_teams_division_alter_teams_location_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Players",
            new_name="Player",
        ),
        migrations.RenameModel(
            old_name="Teams",
            new_name="Team",
        ),
    ]
